### ISSUE TITLE
Seems to install the scripts into the main python directory, rather than "Scripts"

### ISSUE THREAD

**Issue by adamc55** [davidmarble/virtualenvwrapper-win#51]
When I run this, it seems to install the scripts into C:\python27, rather than c:\python27\scripts. That's a problem going forward for those of us using the Python launcher (e.g., see http://testerstories.com/2014/06/multiple-versions-of-python-on-windows/) because that pattern requires keeping the Python directories out of the path.

**Comment by adamc55** [comment]
I got around to looking through the source. Clearly you are doing this intentionally in setup.py with the install class, but it depends on the Python dir being in the path and so breaks the multi-python installation. If I remove that from setup.py it works as expected.

**Comment by utek** [comment]
I like your Pull Request #52. But would like to listen for reasons why @davidmarble put scripts out of /Scripts in the first place. Maybe there is something that we don't see.

**Comment by utek** [comment]
@adamc55 I did some digging and here's David's reasons:
https://github.com/davidmarble/virtualenvwrapper-win/commit/faafb0bb145da039ac397401d1909ea2fd6e1290

**Comment by thebjorn** [comment]
The behavior is surprising (well, I was surprised when this bit me at least ;-)  I'm not sure how common it is to be switching your main Python, rather than just switching virtualenvs?

**Comment by adamc55** [comment]
I don't know how common it is. One scenario would be an organization gradually switching from 2.x to 3. Another would be individuals splitting time between work (2.x) and side projects (3.x).

I read David's explanation but don't totally understand the reasoning. It seems to me that it violates the principle of least surprise in a big way -- if I were switching from 2.x to 3.x, I wouldn't expect a 2.x-based pip install to keep working. I would _expect_ to have to install versions of virtualenwrapper-win in both environments if I wanted to use it in both places. (Or, alternately, I would expect it not to be a Python package, but simply a package of shell scripts.) 

Also, it seems to me that having two Python directories in the path is bad in exactly the same way that having two script directories in the path is -- imagine what would happen if other script authors adopted David's technique? The script path issue is at least mitigated by setuptools' automatic script creation feature, which can generate versions aliased to the python distribution (e.g., pip2 and pip3).

But I acknowledge that it's a complex problem and I don't have special expertise here.

**Comment by thebjorn** [comment]
Does it have something to do with using 2.x and creating a 3.x virtualenv and loosing your virtualenv commands once you enter the 3.x environment unless you keep the directory with the virtualenv .bat files on the path?  The linux version of virtualenv installs into system directories so doesn't run into this issue...

**Comment by utek** [comment]
I have the tool that switch main Python on Windows (replacing both Python and Python\Scripts paths in PATH). So I have to install virtualenvwrapper-win on every main Python instance. 
If I want to create Py2 venv I switch to Py2 and use mkvirtualenv, and switch to Py3 to create Py3 venv. Once created there is no need to switch main python to work on venv. I can call workon on Py3 to switch to venv with Py2.

So venvwrapper-win commands in Python or Python\Scripts are working for me. I prefer latter.

**Comment by davidmarble** [comment]
Thanks @utek for pointing out the commit where I stated my reasons. I don't have an immediate reaction to changing the approach -- that is, I'm open to any change that makes sense for the majority of users. Perhaps we should have a bit more conversation though before we hastily make a change.

Some discussion about why I did what I did: 

One reason for my approach had to do with supporting Python 2.5-2.7 and Python 3.0-3.2. I believe when I looked at it back in early 2013 that the Windows installers didn't add the Scripts directory to your PATH, so I wanted to make it easy based on default installations to have virtualenvwrapper-win work. Also, none of these versions have a python launcher to switch versions and there was no ability to select a default python version without some 3rd party script. That's why I originally wrote [pywin](https://github.com/davidmarble/pywin).

Another reason for my approach is it doesn't make sense to me to have 2+ `\Scripts` directories in the PATH at the same time, because there can be many conflicting executables and potentially scripts you'd accidentally call for the wrong version of Python you thought you were working on. However, it does make sense to me to have 2+ Python root directories on the PATH at the same time, because the only potentially conflicting executables are python.exe and pythonw.exe -- so you only need to worry about which root directory is first in your PATH. Regardless of people's approaches with `\Scripts`, If I could count on root Python directories on the PATH, then virtualenvwrapper-win would always be available. I thought this was the best compromise.

If you're using the new py.exe launcher, and you have more than 1 `\Scripts` directory on your PATH, how do you change which scripts are called when you switch Python versions? (I noticed this came up in the comments on the blog post @adamc55 linked to.) Let's say you don't put multiple `\Scripts` directories on your PATH; you still need some way of switching to a different `\Scripts` directory on your PATH when you switch Python versions. These are some reasons I wrote [pywin](https://github.com/davidmarble/pywin), which handles the PATH ordering changes for you and makes sure only 1 `\Scripts` directory is on the PATH at a time.

There may be some other approaches available today if we can rely on users of virtualenvwrapper-win having Python 3.3 or 3.4, which include the `py.exe` launcher and support for [custom default python versions](https://docs.python.org/3/using/windows.html#customizing-default-python-versions). But I'm not sure even with these latest versions if the `\Scripts` issue is taken care of. Can someone check that out and report back? What happens if you install the latest 2.7 and 3.4 Python versions and check or don't check the "add python.exe to my path" option in the installation, then use `py.exe` and the `PY_PYTHON` environment variable? There are several cases we'd need to cover based on the user's setup. (These are more reasons why sticking with the root directory for these scripts makes sense to me still, but I can be convinced otherwise.) Other ideas for approaches if we can rely on users having 3.3 or 3.4 installed?

I worry a bit about users of old Python versions that have the limitations I encountered when I went with the current approach. However, it's probably fine to start making changes to virtualenvwrapper-win that rely on people having Python 3.3 or 3.4 installed. Older Python users can install a prior version of virtualenvwrapper-win. Let's make this explicit in the documentation if we do this; perhaps even having separate sections in the README for users with Python 3.3+ and those with Python 2.5-3.2.

Thoughts?

**Comment by thebjorn** [comment]
I don't think we can rely on Py3.x being installed yet.  I tried to have both installed for a while - so I could use the new switcher and the included pip, and potentially to start preparing for 3.x.  In the end it was just too much trouble, and while I could usually figure out where things went wrong there was a distinct attitude from other developers that it was very confusing.  What are your thougths about installing to %APPDATA%\virtualenvwrapper ?

**Comment by utek** [comment]
@thebjorn In that case user would have to add %APPDATA%\virtualenvwrapper to system path. So one more step in installation. I don't think that it plays well with `pip install virtualenvwrapper-win`. Natural assumption for me is that after `pip install` command would be working without any additional step.

We would at least add message about it to be shown after `pip install`

**Comment by thebjorn** [comment]
I would assume we would add %APPDATA%\virtualenvwrapper to the User path as part of the installation.

**Comment by piotr-dobrogost** [comment]
*When in Rome, do as the Romans do* :)
I wouldn't try to be smart and would recommend placing scripts in standard location i.e. `\Scripts`. By doing this we benefit from work of community and improvements in the ecosystem (like adding `\Scripts` to the `PATH` by newer Python's installers).

**Comment by thebjorn** [comment]
I thought it was "When in Rome, do a Roman.." :-)

virtualenvwrapper isn't like other python modules though, mostly because it contains "no" python, it just uses python's machinery to install itself (which is an excellent choice).

virtualenvwrapper on linux doesn't install itself anywhere near python, but in /usr/local/bin

On Windows, npm, the node.js package manager, installs `.cmd` files to run globally installed packages in %APPDATA%\npm.

Maybe this isn't as much a question about Romans as about The People's Front (https://www.youtube.com/watch?v=gb_qHP7VaZE) :-)

**Comment by hobbsd** [comment]
+1 for putting the scripts in `\Scripts`. I've never liked having to add a main Python dir to the path for `virtualenvwrapper-win`.

**Comment by davidmarble** [comment]
@hobbsd If you don't like adding the main Python dir to the PATH, how do you run python from the command-line? Or do you not ever do that?

**Comment by hobbsd** [comment]
I always use the `py` launcher that Python3 installs into the `c:\windows` dir. It's a utility that allows you to use shebang lines in your python files -- it has greatly improved Python on Windows.

**Comment by davidmarble** [comment]
Got it. So you're representative of virtualenvwrapper-win users who have 3.3 or 3.4 installed. Good data point.

**Comment by thebjorn** [comment]
For users with multiple Pythons installed.. is the goal to install one virtualenvwrapper that serves all Python installations, or should users install virtualenvwrapper into each Python installation?

**Comment by utek** [comment]
I treat virtualenvwrapper-win as any other python package. So I install it in every Python installation.

**Comment by adamc55** [comment]
That's what I would do as well. To me, pip installations are always bound
to a particular Python installation.

I've been thinking about the point that it's really just a set of shell
scripts that could live anywhere in your path. To me, that suggests that
perhaps it shouldn't be a pip install, although pip allows conveniently
expressing the dependency on virtualenv. But if it is going to be a pip
install, I'd expect to find it in the canonical location (scripts) and to
have to install it separately for each Python installation.

I do wonder about managing script directories in the path in a multi-python
environment. The whole pip2 vs. pip3 approach (i.e., creating unique
aliases for scripts) doesn't seem particularly robust.

**Comment by davidmarble** [comment]
Just like virtualenvwrapper, which installs to /usr/local/bin, this set of utilities belongs in a global directory that's guaranteed to be in someone's PATH.

Could we install these scripts in some other directory that should be on the PATH? For example, look in the PATH when installing for `\Windows\system32` or `\Windows`? Maybe, but would that require they are running the command-line in administrator mode?

If not, maybe I'm ok changing back to `\Scripts` and just telling users with multiple versions of Python that they need to install it once for every version they run.

**Comment by utek** [comment]
Putting scripts in `\Windows\System32`, or `\Windows` would solve problems with `PATH` but I find it rude when something put it's files inside `\Windows` dir. And like you said, user would have to run command line as administrator to install virtualenvwrapper-win.

I think we have two "good" options:
1. Install in `%APPDATA%\virtualenvwrapper`, and ask users to add it to `PATH`
2. Install in `%PYTHON_DIR%\Scripts`, and ask users to install it for every Python version they have

**Comment by thebjorn** [comment]
That is the beauty of %APPDATA% and the User path variable. You don't need to be running as Administrator to write to them. Changing the User path variable (permanently) can easily be done in a script that is automatically done as part of the install. There is no need to ask users to do anything.

Putting executables anywhere under %SYSTEMROOT% is almost never appropriate, and especially not for the number of .bat files we're talking about here.

The trouble with installing virtualenvwrapper in each Python, is that when someone forgets - then does a `mkvirtualenv` to the new Python and presto, `workon` stops working.  That would be surprising to me.

ps: pip is used to install other non-python packages (like jQuery, bootstrap, etc.). Taking advantage of pip as a generic installer (that understands versions and dependencies) is imho a great idea for anything Python related.

**Comment by adamc55** [comment]
Changing variables without asking is likely to be unexpected and might
cause issues. And as a user, I'd find it pretty mysterious if a pip
associated with a global python started installing into %APPDATA%. If you
go that route, some documentation might help.

**Comment by hobbsd** [comment]
I'd like to see `virtualenvwrapper-win` follow the convention of pip, virtualenv, et al. -- install scripts in `\Scripts` and include copies with an appended Python version number if installing in Python3 so that `mkvirtualenv3` (e.g.) would default to using its corresponding Python3 python executable.

**Comment by piotr-dobrogost** [comment]
> Just like virtualenvwrapper, which installs to /usr/local/bin, this set of utilities belongs in a global directory that's guaranteed to be in someone's PATH.

You have a point here. Earlier, when I advised placing scripts into `\Scripts` directory I totally forgot that all scripts are plain `.bat` files. Following virtualenvwrapper makes sense (with adjustment to Windows platform of course). In this case we should find `/usr/local/bin` equivalent and use this.

**Comment by adamc55** [comment]
So if someone pip installs it into two different pythons, then later
uninstalls one, it's gone globally? Seems surprising, to me.

**Comment by utek** [comment]
I'm with @adamc55 on this. Different virtualenvwrapper-win install for every python would allows us also adding some python scripts that could extend virtualenvwrapper-win with functionality unavailable in plain  .bat files.

**Comment by thebjorn** [comment]
@adamc55 has a point in that %APPDATA% is a new and unusual (it's also "hidden" in Explorer). Setting the WORKON variable is already part of the installation instructions, and the linux version of virtualenvwrapper requires the user to source /usr/local/bin/virtualenvwrapper.sh in their .bashrc file. It wouldn't be unheard of to require the user to change the path themselves (although personally I like my environment to be fully cooked and ready to use a new package after I install it). 

@adamc55 also has a point that a straight forward data_files install would lead to problems if the user installed two virtualenwrapper-wins (although I'm not sure why they would do that).

I'm not sure which functionality @utek is thinking of putting in Python files (https://virtualenvwrapper.readthedocs.org/en/latest/design.html seems to apply also in Windows), but there would be nothing stopping us from doing both (installing .bat files in a global location and .py files in /Scripts).

I can also envision solutions where the user can choose on first usage: "Do you want to copy virtualenvwrapper to a global path and set your PATH variable?". With some better thought out text perhaps.

Ultimately, though, I believe that a global directory is most useful and poses least restrictions - but I'm (at least currently) not effected by this so I'll be happy with whatever someone with real-world experience feel is better.

**Comment by utek** [comment]
@thebjorn I'm not sure either. It was just an "in case of" idea. 
I like the solution with asking user at the end of virtualenvwrapper-win install to add to path. Or at least we should inform user about necessity of adding %appdata%\virtualenvwrapper to path.

**Comment by utek** [comment]
Are we waiting for more opinions?

**Comment by demichej** [comment]
I didn't see any response to @hobbsd. I find it very odd that this stuff is not being installed in the Scripts directory. This should all be installed like pip and virtualenv are..... In Scripts and with version numbers as part of the name. That would fix everything and would fit exactly what the other packages do.

**Comment by davidmarble** [comment]
Ok, this has waited long enough. Thank you everyone for the discussion. Direct future questioners to this thread -- there were many issues raised, and there's no perfect solution. Moving forward, by default the scripts will be installed in the default `data_files` directory for the active python installation (`<pythondir>\Scripts\`). Users will need to ensure this directory is in their PATH, and will need to install virtualenvwrapper-win for each python installation.

I like @thebjorn 's idea to have a prompt on first run which would ask the user if they'd like to move the scripts to an `%APPDATA%` sub-directory which the user could add to their path, but I don't have time to write such a utility and have the user's decision checked at the beginning of each script. Any of you are welcome to try adding that yourselves! Note that uninstalling will be more difficult if that option is chosen; I'm not sure if there's a way to write a special uninstall routine to check for that.

As always, I welcome other pull requests. This project could use some tests among other things. Thanks again for the discussion!
